language: php
dist: bionic
os: linux

jobs:
  fast_finish: false
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0
  allow_failures:
    - php: nightly

before_script:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
